"""Shared utilities package."""
from .database import (
    ScyllaDBManager,
    RedisManager,
    KafkaManager,
    S3Manager,
    initialize_schema,
    SCYLLA_SCHEMA,
)
from .helpers import (
    normalize_text,
    compute_hash,
    compute_url_hash,
    extract_doi,
    extract_pmid,
    clean_text,
    truncate_text,
    title_similarity,
    extract_sample_size,
    detect_study_type,
    has_statistical_rigor,
    is_industry_funded,
    has_bad_science_indicators,
    parse_date_string,
    is_recent,
    chunk_list,
    safe_get,
    get_domain,
    classify_source_quality,
)
from .metrics import (
    add_metrics_endpoint,
    ARTICLES_CRAWLED,
    CRAWL_METHOD_USED,
    CONTENT_TYPE_COUNTER,
    EXTRACTION_METHOD,
    QUALITY_FILTER,
    RELEVANCE_FILTER,
    ARTICLES_BY_PROJECT,
    LLM_TOKENS,
    PIPELINE_RUNS,
    PIPELINE_STAGE_ARTICLES,
    PIPELINE_DURATION,
)
from .weekly_report import (
    WeeklyReportArticle,
    WeeklyReportSection,
    build_weekly_report_sections,
    project_area_label,
    render_weekly_feedback_pdf,
    week_year_bounds,
)

__all__ = [
    # Database
    "ScyllaDBManager",
    "RedisManager",
    "KafkaManager",
    "S3Manager",
    "initialize_schema",
    "SCYLLA_SCHEMA",

    # Helpers
    "normalize_text",
    "compute_hash",
    "compute_url_hash",
    "extract_doi",
    "extract_pmid",
    "clean_text",
    "truncate_text",
    "title_similarity",
    "extract_sample_size",
    "detect_study_type",
    "has_statistical_rigor",
    "is_industry_funded",
    "has_bad_science_indicators",
    "parse_date_string",
    "is_recent",
    "chunk_list",
    "safe_get",
    "get_domain",
    "classify_source_quality",

    # Metrics
    "add_metrics_endpoint",
    "ARTICLES_CRAWLED",
    "CRAWL_METHOD_USED",
    "CONTENT_TYPE_COUNTER",
    "EXTRACTION_METHOD",
    "QUALITY_FILTER",
    "RELEVANCE_FILTER",
    "ARTICLES_BY_PROJECT",
    "LLM_TOKENS",
    "PIPELINE_RUNS",
    "PIPELINE_STAGE_ARTICLES",
    "PIPELINE_DURATION",

    # Weekly report helpers
    "WeeklyReportArticle",
    "WeeklyReportSection",
    "build_weekly_report_sections",
    "project_area_label",
    "render_weekly_feedback_pdf",
    "week_year_bounds",
]
