"""Shared utilities package."""
from .database import (
    ScyllaDBManager,
    RedisManager,
    KafkaManager,
    S3Manager,
    initialize_schema,
    SCYLLA_SCHEMA,
)
from .helpers import (
    normalize_text,
    compute_hash,
    compute_url_hash,
    extract_doi,
    extract_pmid,
    clean_text,
    truncate_text,
    title_similarity,
    extract_sample_size,
    detect_study_type,
    has_statistical_rigor,
    is_industry_funded,
    has_bad_science_indicators,
    parse_date_string,
    is_recent,
    chunk_list,
    safe_get,
    get_domain,
    classify_source_quality,
)

__all__ = [
    # Database
    "ScyllaDBManager",
    "RedisManager",
    "KafkaManager",
    "S3Manager",
    "initialize_schema",
    "SCYLLA_SCHEMA",
    
    # Helpers
    "normalize_text",
    "compute_hash",
    "compute_url_hash",
    "extract_doi",
    "extract_pmid",
    "clean_text",
    "truncate_text",
    "title_similarity",
    "extract_sample_size",
    "detect_study_type",
    "has_statistical_rigor",
    "is_industry_funded",
    "has_bad_science_indicators",
    "parse_date_string",
    "is_recent",
    "chunk_list",
    "safe_get",
    "get_domain",
    "classify_source_quality",
]